### ISSUE TITLE
Migrate to Sound Null Safety

### ISSUE THREAD

**Issue by tsvillain** [tsvillain/Wallbay#6]
Sound null safety is now the default for new projects (from Flutter 2.2), adding protection against null reference exceptions and enabling developers to express non-nullable types in their code.

## 📝Task
- [ ] Check if all plugins are updated to NullSafety. If not then find a replacement.
- [ ] Move not null safe code to a new branch named `no-null-safety`. Keep sound null safety code in `master`.
- [ ] If the above task is completed Migrate current code to Sound Null Safety.

**Comment by pedr0luiz** [comment]
Can I work on this?
